apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: corr_id
          matcherRegex: "corr_INC_[A-Za-z0-9_]+"
          url: ""
          urlDisplayLabel: "Correlation ID"
    version: 1
    editable: false
